### ISSUE TITLE
Set keepalive min value to 1

### ISSUE THREAD

**Issue by allustin** [moodleuulm/moodle-local_session_keepalive#3]
We need to set the minimal interval to session timeout with 1, not 10

P.S. PHP 7.1 in production for 1 week work well - thanks for plugin

**Comment by abias** [comment]
Hi Alexey,

thanks for your report. I have added 1, 2 and 5 minutes as new values in 78fdd789bd702856f9b62fea8201ad0d7d9fcfa8 and will publish a new version to the plugin repo today.

May I ask why you need these really short values? Is it just because you have really short session timeouts configured or something else?

Thanks,
Alex

**Comment by allustin** [comment]
@abias we use it for investigate some strange behavior of our student 

* we enable autosave for 1 min and keepalive for 1 min
* after that we enable elastic logs collects from main load balanser with session cookie as a key

we want to investigate why our student start atempt and always wait until quiz end "by time"

**Comment by abias** [comment]
Hi Alexey,

thanks for the information. Then I am glad that my plugin could help you with your debugging :)

Thanks,
Alex
